config/routes.rb
Polis::Application.routes.draw do
  resources :cities do
	resources	:questions
  end

  resources :questions do
	resources	:answers
  end

  get "home/index"

  root :to => 'cities#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  attr_accessible :answerer, :detail
end

app/models/city.rb
class City < ActiveRecord::Base
  attr_accessible :address, :address2, :city, :name, :state, :zip

  has_many	:questions
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :detail, :question

  validates	:question,	:presence => true
  validates	:detail,	:presence => true

  belongs_to	:city
  has_many	:answers

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
 def create
	@question = Question.find(params[:question_id])
	@answer = @question.answers.create(params[:answer])
	redirect_to question_path(@question)
 end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @cities }
    end
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
    @city = City.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @city }
    end
  end

  # GET /cities/new
  # GET /cities/new.json
  def new
    @city = City.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @city }
    end
  end

  # GET /cities/1/edit
  def edit
    @city = City.find(params[:id])
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(params[:city])

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, :notice => 'City was successfully created.' }
        format.json { render :json => @city, :status => :created, :location => @city }
      else
        format.html { render :action => "new" }
        format.json { render :json => @city.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /cities/1
  # PUT /cities/1.json
  def update
    @city = City.find(params[:id])

    respond_to do |format|
      if @city.update_attributes(params[:city])
        format.html { redirect_to @city, :notice => 'City was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @city.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city = City.find(params[:id])
    @city.destroy

    respond_to do |format|
      format.html { redirect_to cities_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.find(params[:id])
    @city = @question.city_id
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @question = Question.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.json
 def create
        @city = City.find(params[:city_id])
        @question = @city.questions.create(params[:question])
        redirect_to city_path(@city)
 end

#  def create
#    @question = Question.new(params[:question])

#    respond_to do |format|
#      if @question.save
#        format.html { redirect_to @question, :notice => 'Question was successfully created.' }
#        format.json { render :json => @question, :status => :created, :location => @question }
#      else
#        format.html { render :action => "new" }
#        format.json { render :json => @question.errors, :status => :unprocessable_entity }
#      end
#    end
#  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to @question, :notice => 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @question.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_answer.html.erb
  <p>
    <b>Citizen:</b>
    <%= answer.answerer %>
  </p>
  <p>
    <b>Answer</b>
    <%= answer.detail %>
  </p>

app/views/answers/_form.html.erb
<%= form_for([@question, @question.answers.build]) do |f| %>
        <div class="field">
                <%= f.label :answerer %><br />
                <%= f.text_field :answerer %>
        </div>
        <div class="field">
                <%= f.label :detail %><br />
                <%= f.text_area :detail %>
        </div>
        <div class="actions">
                <%= f.submit %>
        </div>
<% end %>

app/views/cities/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %><br />
    <%= f.text_field :question %>
  </div>
  <div class="field">
    <%= f.label :detail %><br />
    <%= f.text_area :detail %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<h1>Editing city</h1>

<%= render 'form' %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>

app/views/cities/index.html.erb
<h1>Listing cities</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Address2</th>
    <th>City</th>
    <th>State</th>
    <th>Zip</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cities.each do |city| %>
  <tr>
    <td><%= city.name %></td>
    <td><%= city.address %></td>
    <td><%= city.address2 %></td>
    <td><%= city.city %></td>
    <td><%= city.state %></td>
    <td><%= city.zip %></td>
    <td><%= link_to 'Show', city %></td>
    <td><%= link_to 'Edit', edit_city_path(city) %></td>
    <td><%= link_to 'Destroy', city, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New City', new_city_path %>

app/views/cities/new.html.erb
<h1>New city</h1>

<%= render 'form' %>

<%= link_to 'Back', cities_path %>

app/views/cities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @city.name %>
</p>

<p>
  <b>Address:</b>
  <%= @city.address %>
</p>

<p>
  <b>Address2:</b>
  <%= @city.address2 %>
</p>

<p>
  <b>City:</b>
  <%= @city.city %>
</p>

<p>
  <b>State:</b>
  <%= @city.state %>
</p>

<p>
  <b>Zip:</b>
  <%= @city.zip %>
</p>

<h2>Questions</h2>
<%= render @city.questions %>

<h2>Ask A Question</h2>
<%= render "questions/cityform" %>


<%= link_to 'Edit', edit_city_path(@city) %> |
<%= link_to 'Back', cities_path %>

app/views/home/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to "Questions", questions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Polis</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questions/_cityform.html.erb
<%= form_for([@city, @city.questions.build]) do |f| %>
        <div class="field">
                <%= f.label :question %><br />
                <%= f.text_field :question %>
        </div>
        <div class="field">
                <%= f.label :detail %><br />
                <%= f.text_area :detail %>
        </div>
        <div class="actions">
                <%= f.submit %>
        </div>
<% end %>

app/views/questions/_question.html.erb
  
<table>
  <tr>
    <td><%= question.question %></td>
    <td><%= link_to 'Show', question %></td>
    <td><%= link_to 'Edit', edit_question_path(question) %></td>
    <td><%= link_to 'Destroy', question, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
</table>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Listing questions</h1>

<table>
  <tr>
    <th>Question</th>
    <th>Detail</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @questions.each do |question| %>
  <tr>
    <td><%= question.question %></td>
    <td><%= question.detail %></td>
    <td><%= link_to 'Show', question %></td>
    <td><%= link_to 'Edit', edit_question_path(question) %></td>
    <td><%= link_to 'Destroy', question, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Question:</b>
  <%= @question.question %>
</p>

<p>
  <b>Detail:</b>
  <%= @question.detail %>
</p>

<h2>Answers</h2>
<%= render @question.answers %>

<h2>Answer this Question</h2>
<%= render "answers/form" %>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', city_path(@city) %>